
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 39
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 69
#define YY_END_OF_BUFFER 70
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[355] =
    {   0,
        0,    0,    0,    0,    0,    0,   13,   13,   70,   68,
       58,   60,   61,   59,   57,   53,   12,   67,   52,   68,
       34,   35,   50,   48,   56,   49,   68,   51,   64,   64,
       55,   42,   54,   43,   67,   67,   38,   39,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   36,   68,   37,    7,    6,    3,
        4,    7,   11,    9,    9,   13,   15,   15,   16,   14,
       62,   45,    0,   66,    0,   67,   40,   63,   65,    0,
        1,    8,   65,    0,    0,    0,   64,   64,    0,   46,
       44,   47,   67,   67,   67,   67,   67,   67,   67,   67,

       67,   67,   67,   67,   67,   20,   67,   67,   67,   67,
       67,   67,   67,   67,   24,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   41,    5,    2,   10,   13,    0,
       15,   14,   13,   65,    0,    0,    0,   65,    0,    0,
       65,    0,   64,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   63,   67,   67,   67,   25,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,

        0,   65,    0,   65,    0,    0,   65,   65,    0,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   23,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   18,   32,   67,   67,   65,
        0,    0,   65,    0,   67,   67,   67,   67,   67,   67,
       19,   67,   67,   67,   67,   63,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       63,   67,   67,   33,    0,   67,   31,   63,   67,   67,
       67,   67,   22,   67,   67,   67,   67,   67,   67,   67,

       67,   28,   29,   30,   67,   67,   67,   67,   21,   63,
        0,   67,   17,   67,   67,   67,   67,   67,   67,   67,
       67,   67,    0,    0,   67,   67,   67,   67,   67,   67,
        0,    0,   67,   67,   67,    0,    0,   67,    0,    0,
       67,    0,    0,    0,    0,    0,    0,    0,    0,   26,
        0,    0,   27,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    1,    9,   10,   11,    1,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,    1,   22,   23,
       24,   25,    1,    1,    9,    9,    9,    9,   26,    9,
        9,    9,   27,    9,    9,    9,    9,    9,    9,    9,
        9,    9,   28,    9,    9,    9,    9,    9,    9,    9,
       29,   30,   31,    1,   32,    1,   33,   34,   35,   36,

       37,   38,   39,   40,   41,    9,   42,   43,   44,   45,
       46,   47,    9,   48,   49,   50,   51,   52,   53,   54,
       55,   56,   57,   58,   59,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[60] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    4,    5,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    5,
        5,    1,    1,    1,    1,    5,    5,    5,    1,    1,
        1,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[362] =
    {   0,
        0,    0,   58,   62,   65,   66,   70,   74,  541,  542,
      542,  542,  542,  537,  542,  515,   66,    0,  542,  527,
      542,  542,  542,  522,  542,  519,   60,   69,   69,   73,
      542,  511,  510,  509,  487,   42,  542,  542,   64,   61,
       75,   65,   69,   84,  485,   84,  484,   87,   86,  492,
       91,   92,  482,  487,  542,  468,  542,  542,  542,  542,
      522,  505,  542,  542,  520,  492,  542,  518,  542,  118,
      542,  542,  125,  542,  127,    0,  542,  542,  132,  483,
      542,  542,  141,  153,  130,  160,  168,  175,  177,  542,
      542,  542,  469,  470,  468,  467,  466,  468,  476,  462,

       35,  478,  477,  464,  470,  456,  457,  454,  454,  460,
      457,  455,  452,  449,    0,  451,  110,  452,  446,  442,
      451,  458,  108,  458,  441,  444,  143,  442,  447,  442,
       95,  151,  167,  445,  542,  542,  542,  542,  455,  191,
      542,  542,  454,  193,  203,  183,  438,  196,  217,  162,
      222,  226,  230,  445,  440,  430,  429,  441,  434,  443,
      438,  437,  438,  424,  422,  177,  437,  435,  431,  423,
      429,  416,  431,  430,    0,  416,  214,  411,  423,  420,
      417,  414,  414,  403,  404,  410,  401,  403,  400,  408,
      411,  397,  411,  396,  398,  398,  405,  405,  407,  396,

      244,  248,  399,  250,  252,  254,  257,  265,  270,  398,
      391,  398,  386,  385,  395,  389,  390,  380,  378,  386,
      375,  382,    0,  379,  386,  379,  371,  383,  371,  385,
      369,  364,  382,  381,  376,  371,  363,  360,  368,  373,
      359,  371,  365,  351,  354,    0,    0,  352,  364,  272,
      274,  350,  278,  280,  362,  359,  353,  363,  345,  361,
        0,  348,  349,  354,  354,  346,  344,  337,  341,  347,
      347,  344,  332,  346,  345,  334,  343,  327,  336,  327,
      325,  332,  331,    0,  331,  322,    0,  351,  333,  322,
      315,  315,    0,  315,  308,  325,  326,  327,  322,  321,

      307,    0,    0,    0,  318,  309,  317,  310,  542,  334,
      305,  300,    0,  312,  303,  310,  311,  308,  297,  298,
      294,  299,  288,  283,  280,  283,  274,  273,  267,  257,
      272,  253,  247,  250,  227,  233,  261,  229,  212,  212,
      219,  216,  201,  218,  199,  190,  186,  161,  137,  542,
      127,   94,  542,  542,  312,  317,  322,  327,   81,  332,
      337
    } ;

static yyconst flex_int16_t yy_def[362] =
    {   0,
      354,    1,  355,  355,  356,  356,  357,  357,  354,  354,
      354,  354,  354,  354,  354,  354,  358,  359,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  359,  359,  354,  354,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  360,  354,  354,  354,  361,
      354,  354,  358,  354,  354,  359,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  359,  359,  359,  359,  359,  359,  359,  359,

      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  354,  354,  354,  354,  360,  354,
      354,  354,  360,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,

      354,  354,  354,  354,  354,  354,  354,  354,  354,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  354,
      354,  354,  354,  354,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  354,  359,  359,  359,  359,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,

      359,  359,  359,  359,  359,  359,  359,  359,  354,  359,
      354,  359,  359,  359,  359,  359,  359,  359,  359,  359,
      359,  359,  354,  354,  359,  359,  359,  359,  359,  359,
      354,  354,  359,  359,  359,  354,  354,  359,  354,  354,
      359,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,    0,  354,  354,  354,  354,  354,  354,
      354
    } ;

static yyconst flex_int16_t yy_nxt[602] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   18,   35,   36,   37,   10,
       38,   18,   39,   40,   41,   42,   43,   44,   45,   18,
       46,   18,   47,   18,   48,   18,   49,   50,   51,   52,
       18,   53,   54,   18,   18,   18,   55,   56,   57,   59,
       60,   59,   61,   59,   60,   59,   61,   64,   64,   65,
       65,   62,   67,   74,   68,   62,   67,   69,   68,   79,
       79,   69,   81,  162,  163,   76,   83,   82,   84,   84,
       83,   94,   87,   88,   85,   75,   95,   96,   85,   70,

       86,  105,   80,   70,   89,   85,   98,  101,   99,   85,
      106,  107,   97,  108,  102,  100,  110,  103,  122,  119,
      104,  115,  109,  120,  111,  143,  112,  116,  117,  113,
      126,  131,   74,  123,   73,  194,  124,  121,  353,  132,
      127,  128,  195,  129,  150,  130,  150,  143,  184,  151,
      151,  144,  144,  185,   75,  143,   73,  145,  178,  179,
      148,  148,  143,  146,   73,  143,  149,  143,  145,  352,
       83,   73,   84,   84,   73,  189,   73,  149,   85,  152,
      152,  151,  151,  196,   86,   83,  351,   87,   87,   85,
      190,   86,   83,   85,   87,   88,  153,  153,  139,   89,

       85,  197,  144,  144,   85,  175,   89,  198,   89,  199,
      350,   85,  144,  144,  146,  204,  204,  201,  145,  201,
      139,  149,  202,  202,  146,  219,  220,  205,  139,  145,
      349,  206,  149,  206,  348,  139,  207,  207,  139,  347,
      139,  208,  208,   83,  346,  152,  152,   83,  345,  153,
      153,   85,  344,  209,  175,   85,  228,   86,  343,  229,
      342,   89,   85,  202,  202,  341,   85,  250,  250,  204,
      204,  204,  204,  207,  207,  149,  253,  253,  340,  251,
      339,  205,  338,  205,  208,  208,  149,  175,  254,  208,
      208,  250,  250,  250,  250,  175,  209,  253,  253,  253,

      253,  209,  337,  251,  336,  251,  175,  335,  175,  254,
      175,  254,   58,   58,   58,   58,   58,   63,   63,   63,
       63,   63,   66,   66,   66,   66,   66,   73,  334,  333,
       73,   73,  139,  332,  331,  175,  139,  142,  330,  142,
      142,  142,  329,  175,  328,  327,  326,  325,  175,  175,
      324,  323,  322,  321,  320,  319,  318,  175,  175,  317,
      316,  315,  175,  175,  175,  314,  313,  312,  311,  310,
      309,  308,  307,  175,  306,  175,  305,  304,  303,  302,
      301,  300,  299,  175,  298,  297,  175,  296,  295,  294,
      293,  292,  291,  290,  175,  289,  288,  287,  286,  285,

      284,  283,  282,  281,  280,  279,  175,  278,  277,  175,
      276,  275,  274,  273,  272,  271,  270,  269,  268,  267,
      175,  266,  246,  265,  264,  263,  262,  175,  261,  175,
      175,  260,  259,  258,  257,  256,  255,  252,  249,  248,
      247,  246,  245,  244,  175,  243,  242,  241,  240,  239,
      238,  237,  236,  235,  234,  233,  175,  232,  175,  231,
      230,  175,  227,  226,  225,  224,  175,  223,  222,  221,
      218,  175,  217,  175,  175,  216,  215,  214,  213,  212,
      211,  210,  203,  140,  140,  200,  193,  192,  191,  188,
      187,  186,  183,  182,  175,  181,  180,  177,  176,  175,

      174,  173,  172,  171,  170,  169,  168,  167,  166,  165,
      164,  161,  160,  159,  158,  157,  156,  155,  154,  147,
      141,  140,  138,  137,  136,  135,  134,  133,  125,  118,
      114,   93,   92,   91,   90,   78,   78,   77,   72,   71,
      354,    9,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,

      354
    } ;

static yyconst flex_int16_t yy_chk[602] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        3,    3,    3,    4,    4,    4,    4,    5,    6,    5,
        6,    3,    7,   17,    7,    4,    8,    7,    8,   27,
       27,    8,   28,  101,  101,  359,   29,   28,   29,   29,
       30,   36,   30,   30,   29,   17,   36,   39,   30,    7,

       29,   42,   27,    8,   30,   29,   40,   41,   40,   30,
       42,   43,   39,   43,   41,   40,   44,   41,   49,   48,
       41,   46,   43,   48,   44,   70,   44,   46,   46,   44,
       51,   52,   73,   49,   75,  131,   49,   48,  352,   52,
       51,   51,  131,   51,   85,   51,   85,   70,  123,   85,
       85,   79,   79,  123,   73,   70,   75,   79,  117,  117,
       83,   83,   70,   79,   75,   70,   83,   70,   79,  351,
       84,   75,   84,   84,   75,  127,   75,   83,   84,   86,
       86,  150,  150,  132,   84,   87,  349,   87,   87,   84,
      127,   86,   88,   87,   88,   88,   89,   89,  140,   87,

       88,  132,  146,  146,   87,  132,   88,  133,   89,  133,
      348,   88,  144,  144,  146,  148,  148,  145,  144,  145,
      140,  148,  145,  145,  144,  166,  166,  148,  140,  144,
      347,  149,  148,  149,  346,  140,  149,  149,  140,  345,
      140,  151,  151,  152,  344,  152,  152,  153,  343,  153,
      153,  152,  342,  151,  341,  153,  177,  152,  340,  177,
      339,  153,  152,  201,  201,  338,  153,  202,  202,  204,
      204,  205,  205,  206,  206,  204,  207,  207,  337,  202,
      336,  204,  335,  205,  208,  208,  204,  334,  207,  209,
      209,  250,  250,  251,  251,  333,  208,  253,  253,  254,

      254,  209,  332,  250,  331,  251,  330,  329,  328,  253,
      327,  254,  355,  355,  355,  355,  355,  356,  356,  356,
      356,  356,  357,  357,  357,  357,  357,  358,  326,  325,
      358,  358,  360,  324,  323,  322,  360,  361,  321,  361,
      361,  361,  320,  319,  318,  317,  316,  315,  314,  312,
      311,  310,  308,  307,  306,  305,  301,  300,  299,  298,
      297,  296,  295,  294,  292,  291,  290,  289,  288,  286,
      285,  283,  282,  281,  280,  279,  278,  277,  276,  275,
      274,  273,  272,  271,  270,  269,  268,  267,  266,  265,
      264,  263,  262,  260,  259,  258,  257,  256,  255,  252,

      249,  248,  245,  244,  243,  242,  241,  240,  239,  238,
      237,  236,  235,  234,  233,  232,  231,  230,  229,  228,
      227,  226,  225,  224,  222,  221,  220,  219,  218,  217,
      216,  215,  214,  213,  212,  211,  210,  203,  200,  199,
      198,  197,  196,  195,  194,  193,  192,  191,  190,  189,
      188,  187,  186,  185,  184,  183,  182,  181,  180,  179,
      178,  176,  174,  173,  172,  171,  170,  169,  168,  167,
      165,  164,  163,  162,  161,  160,  159,  158,  157,  156,
      155,  154,  147,  143,  139,  134,  130,  129,  128,  126,
      125,  124,  122,  121,  120,  119,  118,  116,  114,  113,

      112,  111,  110,  109,  108,  107,  106,  105,  104,  103,
      102,  100,   99,   98,   97,   96,   95,   94,   93,   80,
       68,   66,   65,   62,   61,   56,   54,   53,   50,   47,
       45,   35,   34,   33,   32,   26,   24,   20,   16,   14,
        9,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,

      354
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "jac.l"
#line 2 "jac.l"
  #include <stdio.h>
  #include <ctype.h>
  #include <stdarg.h>
  #include "y.tab.h"
  #include "ast.h"
  #include "symbol_table.h"
  #include "code_gen.h"
  #define MAX_SIZE 1024

  int yyparse();
  int col = 1;
  int line = 1;
  static int comment_start_col = 0;
  static int comment_start_line = 0;
  static int string_start_col = 0;
  static int string_start_line = 0;
  static int input_flag = 0;
  static int return_flag = 0;

  extern node* ast;



#line 736 "lex.yy.c"

#define INITIAL 0
#define MULTILINECOMMENT 1
#define COMMENT 2
#define STRINGSTATE 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 36 "jac.l"

#line 955 "lex.yy.c"

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 355 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 542 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 37 "jac.l"
{BEGIN MULTILINECOMMENT; comment_start_col = col; comment_start_line = line; col+=yyleng;}
	YY_BREAK
case YY_STATE_EOF(MULTILINECOMMENT):
#line 38 "jac.l"
{printf("Line %d, col %d: unterminated comment\n", comment_start_line, comment_start_col); col+=1; return 0;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 39 "jac.l"
{col+=yyleng; BEGIN 0;}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 40 "jac.l"
{col=1; line+=1;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 41 "jac.l"
{col=1; line+=1;}
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 42 "jac.l"
{col=1; line+=1;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 43 "jac.l"
{col+=1;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 44 "jac.l"
{col+=yyleng;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 46 "jac.l"
{BEGIN COMMENT;}
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 47 "jac.l"
{col=1; line+=1; BEGIN 0;}
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 48 "jac.l"
{col=1; line+=1; BEGIN 0;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 49 "jac.l"
{col+=yyleng;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 51 "jac.l"
{BEGIN STRINGSTATE; string_start_col = col; string_start_line = line; col+=yyleng;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 52 "jac.l"
{col+=yyleng;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 53 "jac.l"
{printf("Line %d, col %d: invalid escape sequence (%s)\n", line, col, yytext); col+=yyleng;}
	YY_BREAK
case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
#line 54 "jac.l"
{printf("Line %d, col %d: unterminated string literal\n", string_start_line , string_start_col); col = 1; line+=1; BEGIN 0;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 55 "jac.l"
{col+=yyleng; BEGIN 0;}
	YY_BREAK
case YY_STATE_EOF(STRINGSTATE):
#line 56 "jac.l"
{printf("Line %d, col %d: unterminated string literal\n",string_start_line, string_start_col); col=1; return 0;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 58 "jac.l"
{col+=yyleng; if(input_flag) { printf("BOOL\n"); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return BOOL;}}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 59 "jac.l"
{col+=yyleng; if(input_flag) { printf("BOOLLIT(%s)\n", yytext); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return BOOLLIT;}}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 60 "jac.l"
{col+=yyleng; if(input_flag) { printf("CLASS\n"); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return CLASS;}}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 61 "jac.l"
{col+=yyleng; if(input_flag) { printf("DO\n"); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return DO;}}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 62 "jac.l"
{col+=yyleng; if(input_flag) { printf("DOTLENGTH\n"); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return DOTLENGTH;}}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 63 "jac.l"
{col+=yyleng; if(input_flag) { printf("DOUBLE\n"); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return DOUBLE;}}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 64 "jac.l"
{col+=yyleng; if(input_flag) { printf("ELSE\n"); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return ELSE;}}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 65 "jac.l"
{col+=yyleng; if(input_flag) { printf("IF\n"); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return IF;}}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 66 "jac.l"
{col+=yyleng; if(input_flag) { printf("INT\n"); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return INT;}}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 67 "jac.l"
{col+=yyleng; if(input_flag) { printf("PARSEINT\n"); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return PARSEINT;}}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 68 "jac.l"
{col+=yyleng; if(input_flag) { printf("PRINT\n"); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return PRINT;}}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 69 "jac.l"
{col+=yyleng; if(input_flag) { printf("PUBLIC\n"); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return PUBLIC;}}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 70 "jac.l"
{col+=yyleng; if(input_flag) { printf("RETURN\n"); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return RETURN;}}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 71 "jac.l"
{col+=yyleng; if(input_flag) { printf("STATIC\n"); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return STATIC;}}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 72 "jac.l"
{col+=yyleng; if(input_flag) { printf("STRING\n"); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return STRING;}}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 73 "jac.l"
{col+=yyleng; if(input_flag) { printf("VOID\n"); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return VOID;}}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 74 "jac.l"
{col+=yyleng; if(input_flag) { printf("WHILE\n"); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return WHILE;}}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 75 "jac.l"
{col+=yyleng; if(input_flag) { printf("OCURV\n"); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return OCURV;}}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 76 "jac.l"
{col+=yyleng; if(input_flag) { printf("CCURV\n"); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return CCURV;}}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 77 "jac.l"
{col+=yyleng; if(input_flag) { printf("OBRACE\n"); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return OBRACE;}}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 78 "jac.l"
{col+=yyleng; if(input_flag) { printf("CBRACE\n"); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return CBRACE;}}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 79 "jac.l"
{col+=yyleng; if(input_flag) { printf("OSQUARE\n"); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return OSQUARE;}}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 80 "jac.l"
{col+=yyleng; if(input_flag) { printf("CSQUARE\n"); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return CSQUARE;}}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 81 "jac.l"
{col+=yyleng; if(input_flag) { printf("AND\n"); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return AND;}}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 82 "jac.l"
{col+=yyleng; if(input_flag) { printf("OR\n"); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return OR;}}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 83 "jac.l"
{col+=yyleng; if(input_flag) { printf("LT\n"); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return LT;}}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 84 "jac.l"
{col+=yyleng; if(input_flag) { printf("GT\n"); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return GT;}}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 85 "jac.l"
{col+=yyleng; if(input_flag) { printf("EQ\n"); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return EQ;}}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 86 "jac.l"
{col+=yyleng; if(input_flag) { printf("NEQ\n"); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return NEQ;}}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 87 "jac.l"
{col+=yyleng; if(input_flag) { printf("LEQ\n"); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return LEQ;}}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 88 "jac.l"
{col+=yyleng; if(input_flag) { printf("GEQ\n"); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return GEQ;}}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 89 "jac.l"
{col+=yyleng; if(input_flag) { printf("PLUS\n"); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return PLUS;}}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 90 "jac.l"
{col+=yyleng; if(input_flag) { printf("MINUS\n"); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return MINUS;}}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 91 "jac.l"
{col+=yyleng; if(input_flag) { printf("STAR\n"); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return STAR;}}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 92 "jac.l"
{col+=yyleng; if(input_flag) { printf("DIV\n"); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return DIV;}}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 93 "jac.l"
{col+=yyleng; if(input_flag) { printf("MOD\n"); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return MOD;}}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 94 "jac.l"
{col+=yyleng; if(input_flag) { printf("NOT\n"); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return NOT;}}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 95 "jac.l"
{col+=yyleng; if(input_flag) { printf("ASSIGN\n"); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return ASSIGN;}}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 96 "jac.l"
{col+=yyleng; if(input_flag) { printf("SEMI\n"); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return SEMI;}}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 97 "jac.l"
{col+=yyleng; if(input_flag) { printf("COMMA\n"); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return COMMA;}}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 98 "jac.l"
{col+=1;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 99 "jac.l"
{col+=1;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 100 "jac.l"
{col=1; line +=1;}
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 101 "jac.l"
{col=1; line+=1;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 102 "jac.l"
{col+=1;}
	YY_BREAK
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 103 "jac.l"
{col=1; line+=1;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 104 "jac.l"
{col+=yyleng; if(input_flag) { printf("RESERVED(%s)\n", yytext); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return RESERVED;}}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 105 "jac.l"
{col+=yyleng; if(input_flag) { printf("DECLIT(%s)\n", yytext); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return DECLIT;}}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 106 "jac.l"
{col+=yyleng; if(input_flag) { printf("REALLIT(%s)\n", yytext); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return REALLIT;}}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 107 "jac.l"
{col+=yyleng; if(input_flag) { printf("STRLIT(%s)\n", yytext); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return STRLIT;}}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 108 "jac.l"
{col+=yyleng; if(input_flag) { printf("ID(%s)\n", yytext); } if(return_flag) { yylval.token = allocate_structure(line, col - yyleng, yytext); return ID;}}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
#line 109 "jac.l"
{col+=1; return 0;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 110 "jac.l"
{printf("Line %d, col %d: illegal character (%c)\n", line, col, yytext[0]);col+=yyleng;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 111 "jac.l"
ECHO;
	YY_BREAK
#line 1377 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 355 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 355 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 354);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 110 "jac.l"





int main(int argc, char **argv) {
  if(argc > 1){
    if (!strcmp(argv[1], "-l")) {
      input_flag = 1;
      yylex();
    } else if(!strcmp(argv[1], "-1")){
      input_flag = 0;
      return_flag = 0;
      yylex();
    }else if(!strcmp(argv[1], "-2")){
      return_flag = 1;
      yyparse();
    } else if(!strcmp(argv[1], "-t")){
      return_flag = 1;
      yyparse();
      if(!error_flag){
        print_tree(ast, 0);
        //destroy_tree(ast);
      }
    } else if(!strcmp(argv[1], "-s")){
      return_flag = 1;
      yyparse();
      if(!error_flag){
        table_index = 0;
        table = new_table(MAX_SIZE);
        first_traverse(ast);
        create_an_tree(ast);
        print_table();
        printf("\n");
        print_tree(ast,0);
        //destroy_tree(ast);
      }
    } else if(!strcmp(argv[1], "-3")){
       return_flag = 1;
       yyparse();
       if(!error_flag){
        table_index = 0;
        table = new_table(MAX_SIZE);
        first_traverse(ast);
        create_an_tree(ast);
        //destroy_tree(ast);
      }
    }
  } else {
    return_flag = 1;
    yyparse();
    if(!error_flag){
      table_index = 0;
      table = new_table(MAX_SIZE);
      first_traverse(ast);
      create_an_tree(ast);
      //print_table();
      //print_tree(ast,0);
      //code_gen_ast(ast);

    }
  }
  //yylex_destroy();
  return 0;
}

int yywrap() {
  return 1;
}

